apiVersion: apps/v1
kind: Deployment
metadata:
  name: dtm-test-go-2
  labels:
    app: dtm-test-go-2
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: dtm-test-go-2
  template:
    metadata:
      labels:
        app: dtm-test-go-2
    spec:
      containers:
      - name: dtm-test-go-2
        image: "exploitht/dtm-test-go-2:{{ .Chart.AppVersion }}"
        ports:
        - containerPort: 8080
